services:
  kafka:
    build:
      context: debezium-kafka-exporter
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
        JMX_AGENT_VERSION: 0.15.0
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
      - 1977:1977
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - NODE_ID=1
      - NODE_ROLE=combined
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_HEAP_OPTS=-Xms6g -Xmx6g
      - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml
      - JMXHOST=localhost
      - JMXPORT=1977
    mem_limit: 8g
    cpus: 2

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["sh", "/scripts/create-topics.sh"]
    volumes:
      - ./init-scripts:/scripts

  connect:
    build:
      context: debezium-connect-exporter
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
        JMX_AGENT_VERSION: 0.15.0
    container_name: connect
    ports:
     - 8083:8083
     - 1976:1976
    depends_on:
     - kafka
     - kafka-init
    #  - srcmysql
    #  - sinkmysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - KAFKA_CONNECT_HEAP_OPTS=-Xms3g -Xmx3g
     - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml
     - JMXHOST=localhost
     - JMXPORT=1976
    mem_limit: 4g
    cpus: 4

  prometheus:
    build:
      context: debezium-prometheus
      args:
        PROMETHEUS_VERSION: v2.43.0
    container_name: prometheus
    ports:
     - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus     
    mem_limit: 2g
    cpus: 1
    depends_on:
     - connect

  grafana:
    build:
      context: debezium-grafana
      args:
        GRAFANA_VERSION: 9.4.7
    container_name: grafana
    ports:
     - 3000:3000
    environment:
     - DS_PROMETHEUS=prometheus
    mem_limit: 2g
    cpus: 1
    depends_on:
     - prometheus
      
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
    ports:
      - 3001:8080
    mem_limit: 1g
    cpus: 1
    links:
      - kafka
      - connect

networks:
  default:
    name: kafkanet
