services:
  kafka:
    build:
      context: debezium-kafka-exporter
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
        JMX_AGENT_VERSION: 0.15.0
    ports:
      - 9092:9092
      - 9093:9093
      - 1977:1977
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - NODE_ID=1
      - NODE_ROLE=combined
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml
      - JMXHOST=localhost
      - JMXPORT=1977

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["sh", "/scripts/create-topics.sh"]
    volumes:
      - ./init-scripts:/scripts

  srcmysql:
    image: quay.io/debezium/example-mysql:3.3
    container_name: srcmysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "debezium"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpw"
    volumes:
      - ./init-tpcc.sql:/docker-entrypoint-initdb.d/init-tpcc.sql:ro
    depends_on:
      - kafka

  sinkmysql:
    image: quay.io/debezium/example-mysql:3.3
    container_name: sinkmysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "debezium"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpw"
    volumes:
      - ./init-tpcc.sql:/docker-entrypoint-initdb.d/init-tpcc.sql:ro
    depends_on:
      - kafka

  hammerdb-cloudtk:
    image: tpcorg/hammerdb:latest-cloudtk
    container_name: hammerdb
    ports:
      - "3002:8081" 
      - "9082:8082" 
      - "9080:8080"
    depends_on:
      - srcmysql
      - sinkmysql

  connect:
    build:
      context: debezium-connect-exporter
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
        JMX_AGENT_VERSION: 0.15.0
    ports:
     - 8083:8083
     - 1976:1976
    depends_on:
     - kafka
     - kafka-init
     - srcmysql
     - sinkmysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml
     - JMXHOST=localhost
     - JMXPORT=1976

  prometheus:
    build:
      context: debezium-prometheus
      args:
        PROMETHEUS_VERSION: v2.43.0
    ports:
     - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus     
    depends_on:
     - connect

  grafana:
    build:
      context: debezium-grafana
      args:
        GRAFANA_VERSION: 9.4.7
    ports:
     - 3000:3000
    depends_on:
     - prometheus
    environment:
     - DS_PROMETHEUS=prometheus
      
  akhq:
    image: tchiotludo/akhq
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
    ports:
      - 3001:8080
    links:
      - kafka
      - connect

networks:
  default:
    name: grafana
