services:
  sinkmysql:
    image: quay.io/debezium/example-mysql:3.3
    container_name: sinkmysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "debezium"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpw"
    volumes:
      - ./init-tpcc.sql:/docker-entrypoint-initdb.d/init-tpcc.sql:ro
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf:ro
    # mem_limit: 6g
    # cpus: 4
    # depends_on:
    #   - kafka

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: "mysqluser:mysqlpw@(sinkmysql:3306)/"
    ports:
      - "8080:9104"
    depends_on:
      - sinkmysql
    #volumes:
    #  - ./.sinkmy.cnf:/etc/.my.cnf:ro
    command:
      - --config.my-cnf=/cfg/config.my-cnf
    volumes:
      - ./.sinkmy.cnf:/cfg/config.my-cnf:ro

networks:
  default:
    name: sinkmysqlnet
