CREATE DATABASE tpcc;
GRANT ALL PRIVILEGES ON tpcc.* TO 'mysqluser'@'%';
FLUSH PRIVILEGES;
SET GLOBAL max_connections = 500;
CREATE USER 'exporter'@'%' IDENTIFIED BY 'password' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
FLUSH PRIVILEGES;
