startDelaySeconds: 0
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
rules:

  ########################################
  # Kafka Connect Worker Metrics
  ########################################
  - pattern: "kafka.connect<type=connect-worker-metrics>([^:]+):"
    name: "kafka_connect_worker_metrics_$1"

  - pattern: "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
    name: "kafka_connect_metrics_$2"
    labels:
      client: "$1"

  ########################################
  # Kafka Connect Connector & Task Metrics
  ########################################
  # Connector status
  - pattern: "kafka.connect<type=connector-metrics, name=([^,]+)><>Status"
    name: "kafka_connect_connector_status"
    labels:
      connector: "$1"

  # Task status
  - pattern: "kafka.connect<type=connector-metrics, name=([^,]+), task=([^>]+)><>Status"
    name: "kafka_connect_task_status"
    labels:
      connector: "$1"
      task: "$2"

  # Task offset committed total
  - pattern: "kafka.connect<type=connector-task-metrics, connector=([^,]+), task=([^>]+)><>OffsetCommitTotal"
    name: "kafka_connect_task_offset_committed_total"
    labels:
      connector: "$1"
      task: "$2"

  # Task commit rate
  - pattern: "kafka.connect<type=connector-task-metrics, connector=([^,]+), task=([^>]+)><>CommitsTotal"
    name: "kafka_connect_task_commits_total"
    labels:
      connector: "$1"
      task: "$2"

  ########################################
  # Debezium Metrics
  ########################################
  # Rows scanned per table
  - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), key=([^>]+)><>RowsScanned"
    name: "debezium_metrics_RowsScanned"
    labels:
      plugin: "$1"
      context: "$2"
      name: "$3"
      table: "$4"

  # Existing Debezium metrics by task
  - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^,]+), database=([^>]+)>([^:]+)"
    name: "debezium_metrics_$6"
    labels:
      plugin: "$1"
      name: "$2"
      task: "$3"
      context: "$4"
      database: "$5"

  - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^>]+)>([^:]+)"
    name: "debezium_metrics_$5"
    labels:
      plugin: "$1"
      name: "$2"
      task: "$3"
      context: "$4"

  - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+)"
    name: "debezium_metrics_$4"
    labels:
      plugin: "$1"
      name: "$3"
      context: "$2"

  ########################################
  # NEW Debezium Metrics to Monitor Real Lag
  ########################################
  # Source offset lag
  - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^>]+)><>SourceOffsetLag"
    name: "debezium_metrics_source_offset_lag"
    labels:
      plugin: "$1"
      name: "$2"
      task: "$3"
      context: "$4"

  # Pending records in queue
  - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^>]+)><>RecordsPending"
    name: "debezium_metrics_records_pending"
    labels:
      plugin: "$1"
      name: "$2"
      task: "$3"
      context: "$4"

  # Snapshot completion percentage
  - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^>]+)><>SnapshotCompleted"
    name: "debezium_metrics_snapshot_completed"
    labels:
      plugin: "$1"
      name: "$2"
      task: "$3"
      context: "$4"
