{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Source row count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT 'customer' AS table_name, COUNT(*) AS row_count FROM customer \r\nUNION ALL \r\nSELECT 'district', COUNT(*) FROM district \r\nUNION ALL\r\nSELECT 'history', COUNT(*) FROM history \r\nUNION ALL \r\nSELECT 'item', COUNT(*) FROM item \r\nUNION ALL \r\nSELECT 'new_order', COUNT(*) FROM new_order\r\nUNION ALL \r\nSELECT 'order_line', COUNT(*) FROM order_line \r\nUNION ALL \r\nSELECT 'orders', COUNT(*) FROM orders \r\nUNION ALL \r\nSELECT 'stock', COUNT(*) FROM stock \r\nUNION ALL \r\nSELECT 'warehouse', COUNT(*) FROM warehouse;"
    }
   ]
  },
  {
   "title": "Sink row count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT 'customer' AS table_name, COUNT(*) AS row_count FROM cdc_tpcc_customer \r\nUNION ALL \r\nSELECT 'district', COUNT(*) FROM cdc_tpcc_district \r\nUNION ALL \r\nSELECT 'history', COUNT(*) FROM cdc_tpcc_history \r\nUNION ALL \r\nSELECT 'item', COUNT(*) FROM cdc_tpcc_item \r\nUNION ALL \r\nSELECT 'new_order', COUNT(*) FROM cdc_tpcc_new_order\r\nUNION ALL \r\nSELECT 'order_line', COUNT(*) FROM cdc_tpcc_order_line \r\nUNION ALL \r\nSELECT 'orders', COUNT(*) FROM cdc_tpcc_orders \r\nUNION ALL \r\nSELECT 'stock', COUNT(*) FROM cdc_tpcc_stock\r\nUNION ALL \r\nSELECT 'warehouse', COUNT(*) FROM cdc_tpcc_warehouse;"
    }
   ]
  },
  {
   "title": "Source size",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT table_name AS TableName,  ROUND((data_length + index_length) / 1024 / 1024, 2) AS SizeMB\r\nFROM information_schema.tables\r\nORDER BY SizeMB DESC;"
    }
   ]
  },
  {
   "title": "Sink size",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT table_name AS TableName,  ROUND((data_length + index_length) / 1024 / 1024, 2) AS SizeMB\r\nFROM information_schema.tables\r\nORDER BY SizeMB DESC;"
    }
   ]
  }
 ]
}