{
 "title": "WIP",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Bytes In ",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_bytesin_total{job=\"${job}\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_bytesout_total{job=\"${job}\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message in",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_messagesin_total{job=~\"$job\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_log_size{job=~\"$job\"}) /1024 / 1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}